### ISSUE TITLE
Generated enums are string index numbers instead of values.

### ISSUE THREAD

**Issue by mschnee** [PandaDoc/pandadoc-api-node-client#12]
In [DocumentStatusEnum.ts](./src/models/DocumentStatusEnum.ts), the generated Enum is:
```ts
export type DocumentStatusEnum = "0" | "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9" | "10" | "11" | "12";
```

However, the actual values used and returned by Pandadoc's API are:
```ts
export enum DocumentStatusEnum {
  New = 'document.new',
  Draft = 'document.draft',
  Ready = 'document.ready'
}
```

The OpenAPI 3.x spec should look something like this:
```json
"components": {
  "schemas": {
    "DocumentStatusEnum": {
      "type": "string",
      "enum": [
        "document.new",
        "document.draft",
      ]
    }
  }
}
```

**Comment by dimaTimoshenko** [comment]
@mschnee that's right. We use numeric values for document status in query parameters of document list endpoint (like `0`, `1`, `2`) and string values (like `document.drafr`) in responses. For more convenience we added `DocumentStatusRequestEnum.ts`(numeric values) and `DocumentStatusEnum.ts`(string values) in version 4.1.0 of SDK. Both of them listed in openapi schema

**Comment by dimaTimoshenko** [comment]
<img width="1440" alt="Screenshot 2022-01-11 at 14 03 56" src="https://user-images.githubusercontent.com/93124358/148939614-7cd0e3db-c8e5-441d-a267-3a65040a40b2.png">
<img width="1440" alt="Screenshot 2022-01-11 at 14 04 03" src="https://user-images.githubusercontent.com/93124358/148939637-441c1c5f-9850-44bb-b27c-9ee73e20ecbe.png">
