### ISSUE TITLE
Incorrect baseName for attribute in PricingTableRequestRowData

### ISSUE THREAD

**Issue by SiestaMadokaist** [PandaDoc/pandadoc-api-node-client#18]
### Bug Report
According to the documentation: https://developers.pandadoc.com/reference/new-document
the field on `pricing_tables.sections.rows.data` should be something like:
`Name`, `Description`, `Price`, `QTY`, etc. (in CapitalFirstFormat)

however, in the code as can be seen at : https://github.com/PandaDoc/pandadoc-api-node-client/blob/main/src/models/PricingTableRequestRowData.ts
their baseName is `name`, `description`, `price`, and `qty`. (still in lowercase)

when I tried in my own account, using the parameter as shown in the example at https://developers.pandadoc.com/reference/new-document
throw an Error that I'm missing the variable `Name`, `Description`, `Price`, `QTY`.

If I forcefully put the parameter as `Name`, instead of `name`, the parameter will still be ignored, and not sent through the network.

well, the simple solution, would be just to update the baseName in PricingTableRequestRowData.ts if it doesn't break compatibility or something.

**Comment by akutsanov** [comment]
Hello, thank you for your attention and sorry to hear that you are faced with it.
We released Data Merge https://developers.pandadoc.com/changelog/data-merge-for-pricing-tables-via-api and didn't have time to update this case in SDK. Currently, the pricing table row has a flexible structure and `PricingTableRequestRowData` is redundant. It'll be deleted.

To avoid an error, you can just use JSON in the request payload.
https://github.com/PandaDoc/pandadoc-api-node-client/blob/main/examples/createDocumentFromPandadocTemplateAndSend.ts
