### ISSUE TITLE
Metadata filtering not supported

### ISSUE THREAD

**Issue by HarrisonJackson** [PandaDoc/pandadoc-api-node-client#19]
The api docs, sdk docs, and typescript indicate that metadata is supported as a filter parameter for the document list endpoint however I get a 400 or other errors however I try to use it. Below I am using typescript to enforce the expected usage but it still errors out.

SDK Request
```typescript
const client = await getPandaDocDocumentsAPIInstance();
const body: PandaDocAPI.DocumentsApiListDocumentsRequest = {
  metadata: 'metadata_test=testvalue',
};
const documentsResponse = await client.listDocuments(body);
```

SDK Response
```sh
HTTP-Code: 400
Message: Bad Request
Body: {"type":"request_error","detail":{"non_field_errors":["Unsupported parameters passed: 'metadata'."]}}
Headers: {...}
```

**Comment by akutsanov** [comment]
Thank you @HarrisonJackson for your attention. We'll investigate and fix it

**Comment by akutsanov** [comment]
New version 5.0.1 with the fix was released
Please use:
```
const body: PandaDocAPI.DocumentsApiListDocumentsRequest = {
  metadata: ['metadata_test=testvalue', 'metadata_another=another_value']
};
```
