### ISSUE TITLE
DocumentsApi.createDocument does not support file upload

### ISSUE THREAD

**Issue by KidLinus** [PandaDoc/pandadoc-api-node-client#29]
There is no way to uload our PDF's to the pandadoc api using the client. Attachments however can be uploaded. This blocks us from using this api client.

**Comment by amelishko** [comment]
Hey KidLinus,

That's true, this client doesn't support the direct upload of PDFs. As an alternative, you can consider creating a document from PDF uploaded somewhere else, check this example: https://github.com/PandaDoc/pandadoc-api-node-client/blob/main/examples/createDocumentFromPdfUrlAndSend.ts 

If this workaround doesn't work for you, consider using API directly like this: https://developers.pandadoc.com/docs/upload-and-send-a-local-pdf . You can base your code on this client and create a pull request to add this functionality.

Thanks!
Mick
