### ISSUE TITLE
Missing API Parameters - forwarding_settings

### ISSUE THREAD

**Issue by cosmictoby** [PandaDoc/pandadoc-api-node-client#31]
Hi Team,

Client is missing `forwarding_settings` parameters in `sendDocument` function. 

Refer to body params: https://developers.pandadoc.com/reference/send-document

**Comment by maria-yermakovich** [comment]
Thanks for noticing! The field was added in scope of [v6.1.0](https://github.com/PandaDoc/pandadoc-api-node-client/releases/tag/v6.1.0):.
